### ISSUE TITLE
README.md should contain some more info on altcoin options in set_vars.bat

### ISSUE THREAD

**Issue by cassiniNMC** [phelix/easywinbuilder#1]
In README.md:

> Edit set_vars.bat to change the Bitcoin version or build similarly structured altcoins ...

It would be helpful if you could list the altcoins that can be built using easywinbuilder, and which ones have been tested recently.

**Comment by phelixbtc** [comment]
The readme now contains a bit of info about alts. Also https://github.com/phelix/easywinbuilder/commit/45c9238d2469dd9eaa145ffa4cbe818ec6bedfe7 should make it easier to set variables for altcoins.  
testing information can be posted in the forum thread - I don't want to go through the hassle to keep this up to date on github. Closing.

**Comment by cassiniNMC** [comment]
> The **readme** now contains a bit of info about alts.

ok, set_vars.bat now makes the guesswork slightly less cumbersome. There haven't been any changes to the readme file recently, though:
https://github.com/phelix/easywinbuilder/commits/master/README.md

**Comment by phelixbtc** [comment]
> There haven't been any changes to the readme file recently, though:
> That is because I thought so far ahead :)
